import type { SVGProps } from "react";

export type IconProps = SVGProps<SVGSVGElement>;

export * from "./IconBrand";
export * from "./IconBrandLogo";
export * from "./IconHomeFilled";
export * from "./IconSearch";
export * from "./IconSearchFilled";
export * from "./IconHome";
export * from "./IconExplore";
export * from "./IconExploreFilled";
export * from "./IconReels";
export * from "./IconReelsFilled";
export * from "./IconDirectFilled";
export * from "./IconDirect";
export * from "./IconHeart";
export * from "./IconHeartFilled";
export * from "./IconThreads";
export * from "./IconMenu";
export * from "./IconMenuFilled";
export * from "./IconCreate";
export * from "./IconCreateFilled";
export * from "./IconX";
export * from "./IconPost";
export * from "./IconLiveVideo";
export * from "./IconSettings";
export * from "./IconYourActivity";
export * from "./IconSaved";
export * from "./IconTheme";
export * from "./IconReport";
